// offersData.js
const faqData = [
  {
    id: 1,
    question: "How can I contact customer support?",
    answer: "You can contact our customer support through the Contact Us page.",
  },
  {
    id: 2,
    question: "What are the modes of transfer available?",
    answer: "You as a customer can withdraw money or send money to another customer of our bank. To deposit money, please contact our bank employee",
  },
  {
    id: 3,
    question: "How transactions are made secure?",
    answer: "You will get time - based OTP (valid for 2 minutes only) on your email resgistered with us. We generate OTP at our bank servers and when you enter the reveived otp, the otp is verified by our servers and transactions are carried out accordingly.",
  },
  {
    id: 4,
    question: "How can I stop transactions on my account if my login credentials are leaked?",
    answer: "You can reset the password and you will get a new autogenerated password on your mail which you can use for login and please change password after login in Other Services section. We recommend to contact our bank employees and report them. They will freeze/deactivate your account temporarily and reactivate after your request. Please do not panic, we will assist you for all your security needs.",
  },  
  {
    id: 5,
    question: "My Transfer Within Bank (Send money to another customer of bank) is failing",
    answer: "Either you or the other customer has pending KYC or de-activated / freeze account. Please contact our bank employees for the assistance requied and for more info",
  }
];

export default faqData;
